### ISSUE TITLE
Ajouter un exemple de déploiement de site statique hébergé sur github

### ISSUE THREAD

**Issue by mborne** [mborne/k8s-exemples#1]
> initContainers & emptyDir

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cours-devops
  name: cours-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cours-devops
  template:
      labels:
        app: cours-devops
    spec:
      initContainers:
      - image: alpine/git
        name: download
        command: ["/bin/sh","-c","git clone https://github.com/mborne/cours-devops && mv cours-devops/docs/* /usr/share/nginx/html/."]
        volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html
      containers:
      - image: nginx:1.14.2
        name: nginx
        volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www-data
        emptyDir: {}
```
