### ISSUE TITLE
RBAC - Ajouter un exemple pod-kubectl avec des droits restreints

### ISSUE THREAD

**Issue by mborne** [mborne/k8s-exemples#8]
## Draft

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: kubectl-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubectl
  name: kubectl
spec:
  serviceAccountName: kubectl-sa
  containers:
  - command: ["/bin/sleep","3600"]
    image: alpine/k8s:1.28.4
    name: kubectl
  restartPolicy: Never
```
